### ISSUE TITLE
Notes from [Community meeting 2023-09]

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo-catalog#208]
- [x] Update catalog overview table --> done #205 
 - [x] WissGrid-link is broken, please update --> done #207 
 - [x] file format, size: final or raw data? --> es gibt eine Frage dazu; im Allgemeinen kann eine Version von der anderen durch den Skript generiert werden; sinnvoller Schwellenwert = 1 GB
 - [x] Offer possibility to replace "dataset" with "group of similar datasets" --> possibly solved by #84 (s. also discussion in #78 )

**Comment by Zack-83** [comment]
Mögliche Lösung:
* im `<verbose_name>` "dataset" mit "dataset / group" flächendeckend ersetzen
* aufpassen, welche Unterattribute dann als Sammlung gesetzt werden müssen: z. B. "PID"

--> StG / EG verständigen

**Comment by Zack-83** [comment]
Concerning the 3rd point
> file format, size: final or raw data?

Also requested by IMB

Apparently there is a question distinguishing raw from publication-ready data. We could just specify in the help text what are needed, or let the project coordinator explicitely choose. Generally it is advisable to refer only one of the two version and possibly the script used for producing the one from the other.

For size in particular, a meaningful threshold value is 1 GB (below that most repositories, including Zenodo and RADAR, accept data without any special agreements).

@sa-wetter @yasmindemerdash Is this enough for you?
